# Generated by Django 5.1.2 on 2025-11-07 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('category', models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('playing_position', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, default='default_player.png', null=True, upload_to='player_photos/')),
                ('institution_name', models.CharField(help_text='School / College / Village name', max_length=200)),
                ('registration_number', models.CharField(editable=False, max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament_consent', models.ForeignKey(blank=True, help_text='Tournament you agree to play in', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournaments.tournament')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
